#from snakemake.utils import min_version
#min_version("6.0")
#
# module last_workflow:
#     snakefile:"rules/last.smk"
#     config:config
# use rule * from last_workflow
#
# module bowtie_workflow:
#     snakefile:"rules/bowtie.smk"
#     config:config
# use rule* from bowtie_workflow
from snakemake.utils import Paramspace
import pandas as pd

#last_paramspace = Paramspace(pd.read_csv("params/last_params.tsv",sep="\t"))
bowtie2_paramspace = Paramspace(pd.read_csv("params/bowtie2_params.tsv",sep="\t"))

#include:"rules/last.smk"
include:"rules/bowtie.smk"

rule all: #Initial Rule in snakemake
    input:
        #expand("{out_dir}/bowtie2_alignments/{sample_id}/{params}.sam",out_dir = config["out_dir"],sample_id=config["reads"].keys(),params=bowtie2_paramspace.instance_patterns),
        expand("{out_dir}/bowtie2_alignments/{sample_id}.{params}.sam",
                out_dir = config["out_dir"],sample_id=config["reads"].keys(),params=bowtie2_paramspace.instance_patterns)
        #expand("{out_dir}/last_alignments/{sample_id}.{params}.tab",
        #        out_dir = config["out_dir"],sample_id=config["reads"].keys(),params=last_paramspace.instance_patterns)
