reference: /data-ss-2/data-hiv/reference/hxb2.fa

reads:
    SRR4071737:
        [/data-ss-2/data-hiv/reads/nicaragua/SRR4071737/SRR4071737_1.fastq.gz, /data-ss-2/data-hiv/reads/nicaragua/SRR4071737/SRR4071737_2.fastq.gz]
    SRR4071738:
        [/data-ss-2/data-hiv/reads/nicaragua/SRR4071738/SRR4071738_1.fastq.gz, /data-ss-2/data-hiv/reads/nicaragua/SRR4071738/SRR4071738_2.fastq.gz]
    SRR4071739:
        [/data-ss-2/data-hiv/reads/nicaragua/SRR4071739/SRR4071739_1.fastq.gz, /data-ss-2/data-hiv/reads/nicaragua/SRR4071739/SRR4071739_2.fastq.gz]
    SRR4071740:
        [/data-ss-2/data-hiv/reads/nicaragua/SRR4071740/SRR4071740_1.fastq.gz, /data-ss-2/data-hiv/reads/nicaragua/SRR4071740/SRR4071740_2.fastq.gz]
    SRR4071741:
        [/data-ss-2/data-hiv/reads/nicaragua/SRR4071741/SRR4071741_1.fastq.gz, /data-ss-2/data-hiv/reads/nicaragua/SRR4071741/SRR4071741_2.fastq.gz]

out_dir:
    /data-ss-2/data-hiv/alns_params/nicaragua

#training: "yes"
last_param_space_file: "params/last_params.tsv" #path relative to top folder
bowtie2_param_space_file: "params/bowtie2_params.tsv"
