reference: "test_data/hxb2.fasta"
reads:
    my_sample:
        [test_data/sample_1.fastq.gz, test_data/sample_2.fastq.gz]

out_dir:
    test_out

#################
## Aligner Configuration
#################
# Currently supports 'bowtie2' and 'last'
aligner: "last"

# parameters for LAST
last_params:
  [
   ["param_group_name"],
   ["1"]
  ]
