# Template config file.
# Here you can specify the paths to the input and output, and other additional parameters.
# Arguments are specified in a key:value format, do NOT change the key names, unless specified.

###################
##Input and Output
##################

# It is recommended to provide absolute paths, i.e. beginning with root (/).
# Else, paths are considered to be relative to the top-level directory of this software.

#Reference
reference:
    "/path/to/reference/genome"


# Reads
reads:
    my_sample_1: #You can change the name of the sample.
        [/path/to/sample_1_1.fastq.gz, /path/to/sample_1_2.fastq.gz]
        #Provide the paths to the paired-end fastq or fastq.gz files. Do not remove [ and ]. Separate file name by a comma.
        # It is recommended to provide absolute paths, i.e. beginning with root (/).
        # Else, paths are considered to be relative to the top-level directory of this software.
    my_sample_2: #add more samples as needed
        [/path/to/sample_2_1.fastq.gz, /path/to/sample_2_2.fastq.gz]

out_dir:
    /path/to/output/folder


#################
## Aligner Configuration
#################
# Currently supports 'bowtie2' and 'last'
aligner: bowtie2

#Proceed below if you wish to edit default parameters of the different software in this pipeline.

#Currently only some parameters of Bowtie2 can be specified.

#################
## Parameters for Bowtie 2
#################
bowtie2_params:
  [
   ["param_group_name","preset"], #!do not edit this!
   #param_group_name is an arbitrary name for this parameter combination.
   #Preset is a Bowtie2 option that fine-tunes the mapping results.
   #Populate the array below with your choice of parameters.
   ["1","sensitive-local"]
   #add more if you wish to re-run the pipeline with other parameter settings.
  ]

#################
## Parameters for LAST
#################
last_params:
  [
   ["param_group_name"], #!do not edit this!
   #param_group_name is an arbitrary name for this parameter combination.
   ["1"]
   #add more if you wish to re-run the pipeline with other parameter settings.
  ]
