# Template config file.
# Here you can specify the paths to the input and output, and other additional parameters.
# Arguments are specified in a key:value format, do NOT change the key names, unless specified.

###################
##Input and Output
##################

# It is recommended to provide absolute paths, i.e. beginning with root (/).
# Else, paths are considered to be relative to the top-level directory of this software.

#Reference
reference:
    "test_data/hxb2.fasta"
    
reference_name:
    # "subtypeB"
    # "subtype01_AE"
    # "subtype02_AG"
    "hxb2"

hxb2:
    # "test_data/subtypeB.fasta"
    # "test_data/subtype01_AE.fasta"
    "test_data/subtype02_AG.fasta"

virus_gen:
    "ref_viruses_rep_genomes"

# Geographic Location
country:
    "Germany"

# Reads
reads:
    ERR9814511: #You can change the name of the sample.
        ["test_data/germany/ERR9814511/ERR9814511_1.fastq.gz", "test_data/germany/ERR9814511/ERR9814511_2.fastq.gz"]
    ERR9814512:
        ["test_data/germany/ERR9814512/ERR9814512_1.fastq.gz", "test_data/germany/ERR9814512/ERR9814512_2.fastq.gz"]
    ERR9814513:
        ["test_data/germany/ERR9814513/ERR9814513_1.fastq.gz", "test_data/germany/ERR9814513/ERR9814513_2.fastq.gz"]
    # ERR9814514:
    #     ["test_data/germany/ERR9814514/ERR9814514_1.fastq.gz", "test_data/germany/ERR9814514/ERR9814514_2.fastq.gz"]
    # ERR9814515:
    #     ["test_data/germany/ERR9814515/ERR9814515_1.fastq.gz", "test_data/germany/ERR9814515/ERR9814515_2.fastq.gz"]

out_dir:
    "test_out"

#################
## Aligner Configuration
#################
# Currently supports 'bowtie2', 'last', and 'last_trained'
aligner: "last"


#Proceed below if you wish to edit default parameters of the different software in this pipeline.

#Currently only some parameters of Bowtie2 can be specified.

#################
## Parameters for Bowtie 2
#################
bowtie2_params:
  [
   ["param_group_name","preset"], #!do not edit this!
   #param_group_name is an arbitrary name for this parameter combination.
   #Preset is a Bowtie2 option that fine-tunes the mapping results.
   #Populate the array below with your choice of parameters.
   ["1","sensitive-local"]
   #add more if you wish to re-run the pipeline with other parameter settings.
  ]

#################
## Parameters for LAST
#################
last_params:
  [
   ["param_group_name","match","mismatch","gapOpen","gapExtend"],
   ["1",2,3,5,2]
   #add more if you wish to re-run the pipeline with other parameter settings.
  ]

#training: "yes"
last_param_space_file: "params/last_params.tsv" #path relative to top folder
bowtie2_param_space_file: "params/bowtie2_params.tsv"
