# Template config file.
# Here you can specify the paths to the input and output, and other additional parameters.
# Arguments are specified in a key:value format, do NOT change the key names, unless specified.

###################
##Input and Output
##################

# It is recommended to provide absolute paths, i.e. beginning with root (/).
# Else, paths are considered to be relative to the top-level directory of this software.

#Reference
reference:
    # "test_data/hxb2.fasta"
    # "test_data/CRF01_AE.fasta"
    "test_data/subtypeB.fasta"
    
reference_name:
    "subtypeB"
    # "subtype01_AE"
    # "subtype02_AG"
    # "hxb2"
    # "CRF01_AE"

hxb2:
    "test_data/hxb2.fasta"
    # "test_data/subtypeB.fasta"
    # "test_data/subtype01_AE.fasta"
    # "test_data/subtype02_AG.fasta"

virus_gen:
    "ref_viruses_rep_genomes"

# Geographic Location
country:
    "Puerto_Rico"

# Reads
reads:
    # SRR7467888: #You can change the name of the sample.
    #     ["test_data/puerto_rico/SRR7467888/SRR7467888_1.fastq.gz", "test_data/puerto_rico/SRR7467888/SRR7467888_2.fastq.gz"]
    # SRR7467889:
    #     ["test_data/puerto_rico/SRR7467889/SRR7467889_1.fastq.gz", "test_data/puerto_rico/SRR7467889/SRR7467889_2.fastq.gz"]
    SRR7467890:
        ["test_data/puerto_rico/SRR7467890/SRR7467890_1.fastq.gz", "test_data/puerto_rico/SRR7467890/SRR7467890_2.fastq.gz"]
    SRR7467891:
        ["test_data/puerto_rico/SRR7467891/SRR7467891_1.fastq.gz", "test_data/puerto_rico/SRR7467891/SRR7467891_2.fastq.gz"]
    SRR7467892:
        ["test_data/puerto_rico/SRR7467892/SRR7467892_1.fastq.gz", "test_data/puerto_rico/SRR7467892/SRR7467892_2.fastq.gz"]

out_dir:
    "test_out"

#################
## Aligner Configuration
#################
# Currently supports 'bowtie2', 'last', and 'last_trained'
aligner: "last"


#Proceed below if you wish to edit default parameters of the different software in this pipeline.

#Currently only some parameters of Bowtie2 can be specified.

#################
## Parameters for Bowtie 2
#################
bowtie2_params:
  [
   ["param_group_name","preset"], #!do not edit this!
   #param_group_name is an arbitrary name for this parameter combination.
   #Preset is a Bowtie2 option that fine-tunes the mapping results.
   #Populate the array below with your choice of parameters.
   ["1","sensitive-local"]
   #add more if you wish to re-run the pipeline with other parameter settings.
  ]

#################
## Parameters for LAST
#################
last_params:
  [
   ["param_group_name","match","mismatch","gapOpen","gapExtend"],
   ["1", 6, 18, 21, 9]
   #add more if you wish to re-run the pipeline with other parameter settings.
  ]

#training: "yes"
last_param_space_file: "params/last_params.tsv" #path relative to top folder
bowtie2_param_space_file: "params/bowtie2_params.tsv"
