reference: /data-ss-2/data-hiv/reference/hxb2.fa

reads:
    DRR030218:
        [/data-ss-2/data-hiv/reads/nagoya/DRR030218/DRR030218_1.fastq.gz, /data-ss-2/data-hiv/reads/nagoya/DRR030218/DRR030218_2.fastq.gz]
    DRR030219:
        [/data-ss-2/data-hiv/reads/nagoya/DRR030219/DRR030219_1.fastq.gz, /data-ss-2/data-hiv/reads/nagoya/DRR030219/DRR030219_2.fastq.gz]
    DRR030220:
        [/data-ss-2/data-hiv/reads/nagoya/DRR030220/DRR030220_1.fastq.gz, /data-ss-2/data-hiv/reads/nagoya/DRR030220/DRR030220_2.fastq.gz]
    DRR030221:
        [/data-ss-2/data-hiv/reads/nagoya/DRR030221/DRR030221_1.fastq.gz, /data-ss-2/data-hiv/reads/nagoya/DRR030221/DRR030221_2.fastq.gz]
    DRR030222:
        [/data-ss-2/data-hiv/reads/nagoya/DRR030222/DRR030222_1.fastq.gz, /data-ss-2/data-hiv/reads/nagoya/DRR030222/DRR030222_2.fastq.gz]

out_dir:
    /data-ss-2/data-hiv/alns_params/nagoya

#training: "yes"
last_param_space_file: "params/last_params.tsv" #path relative to top folder
bowtie2_param_space_file: "params/bowtie2_params.tsv"
